### ISSUE TITLE
Add make gcc musl-dev packages to alpine image

### ISSUE THREAD

**Issue by stmllr** [Starefossen/docker-ruby-node#11]
Add `make gcc musl-dev` packages to alpine image. These packages are the minimal requirements when installing ffi based ruby gems.

For example, when installing gems for jekyll, ffi is required.

**Comment by stmllr** [comment]
btw. thanks for your images. They solve my real world problems :)

**Comment by radeno** [comment]
I can't speak for @Starefossen but idea of theses Docker images are merge two official Ruby and Node images into one. Adding new layers of complexity and differences from original images could lead to misunderstand when are used.

Use is simple, here you get two images into one, but read official documentation.

**Comment by Starefossen** [comment]
As @radeno mentions, the purpose of this image is to provide an unmodified as possible merge of the official Docker image and the official Ruby image. I am not inclined to add additional packages if they are not included in their respective base images.

Out of curiosity, how does adding `make gcc musl-dev` impact the image size?

**Comment by stmllr** [comment]
The [README](https://github.com/Starefossen/docker-ruby-node#why-nodejs-and-ruby-together) mentions jekyll as an application, which this image is build for.

However installing jekyll fails with the alpine image. That's the reason why I opened this issue.

Steps to reproduce:
```
$ mkdir /tmp/test
$ cat <<EOF > /tmp/test/Gemfile
source "http://rubygems.org"

gem 'jekyll'
EOF
$ docker run -it --rm -v /tmp/test:/app -w /app starefossen/ruby-node:2-6-alpine bundle install                         
Fetching gem metadata from http://rubygems.org/..............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies...
Fetching public_suffix 3.0.0
Installing public_suffix 3.0.0
Using bundler 1.15.4
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching ffi 1.9.18
Installing ffi 1.9.18 with native extensions
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching rb-fsevent 0.10.2
Installing rb-fsevent 0.10.2
Fetching kramdown 1.14.0
Installing kramdown 1.14.0
Fetching liquid 4.0.0
Installing liquid 4.0.0
Fetching mercenary 0.3.6
Installing mercenary 0.3.6                                                                                                                                                  
Fetching rouge 1.11.1                                                                                                                                                       
Installing rouge 1.11.1                                                                                                                                                     
Fetching safe_yaml 1.0.4                                                                                                                                                    
Installing safe_yaml 1.0.4                                                                                                                                                  
Fetching addressable 2.5.2                                                                                                                                                  
Installing addressable 2.5.2                                                                                                                                                
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.                                                                                                          

    current directory: /app/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20170830-1-pxudci.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/local/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:658:in `try_ldflags'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:1818:in `pkg_config'
        from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /app/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /app/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18 for inspection.
Results logged to /app/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.9.18/gem_make.out

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

In Gemfile:
  jekyll was resolved to 3.5.2, which depends on
    jekyll-sass-converter was resolved to 1.5.0, which depends on
      sass was resolved to 3.5.1, which depends on
        sass-listen was resolved to 4.0.0, which depends on
          rb-inotify was resolved to 0.9.10, which depends on
            ffi
```

**Comment by radeno** [comment]
@stmllr This image isn't for Jekyll. It was an example that Jekyll or Rails with webpacker require both Ruby and Node. No they are compatible with Jekyll. Not even Rails doesn't work with Alpine image because Nokogiri.

Again, this is combination of https://hub.docker.com/_/ruby/ and https://hub.docker.com/_/node/ nothing more.

**Comment by stmllr** [comment]
```
$ mkdir /tmp/image
$ cat <<EOF > /tmp/image/Dockerfile
FROM starefossen/ruby-node:2-6-alpine

RUN apk add --no-cache make gcc musl-dev
EOF
$ docker build -t starefossen-support-jekyll /tmp/image
$ docker images  --format "{{.Repository}}: {{.Size}}"  | grep starefossen
starefossen-support-jekyll: 199MB
starefossen/ruby-node: 111MB

**Comment by stmllr** [comment]
@radeno README is broken. I agree.

**Comment by radeno** [comment]
@stmllr significant change in size with `gcc` and `musl-dev` i think they have so many dependencies.

Readme is fine. Second sentence says: `Both Ruby and Node.js are based on official images.`
What you pointing is in section why was this docker image created, no what is supported :)

We could emphasize in readme this image use same packages as official images do.
